version: 0.10.1.{build}
os: 
- Visual Studio 2017
install:
- echo %appveyor_build_worker_image%
- appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0-preview3/nuget.exe
- nuget | findstr /psi "version"

- ps: write-host "before vs command prompt:"
- ps: $env:Path -split ';' | findstr /psi "msbuild"; cmd /c where msbuild.exe

- ps: write-host "calling vs command prompt:"
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat" 

- ps: write-host "after vs command prompt:"
- ps: $env:Path -split ';' | findstr /psi "msbuild"; cmd /c where msbuild.exe

# workaround
#- ps: write-host "applying workaround:"
#- ps: $env:Path = ([System.String]::Join(";", ($env:Path -split ";" | select-string "^(?!.*\\\\MSBuild).*")))
#- ps: $env:Path = ([System.String]::Join(";", ($env:Path -split ";" | select-string "^(?!.*\\MSBuild\\15.0\\bin\\Roslyn).*")))
#- ps: $env:Path = ([System.String]::Join(";", ($env:Path -split ";" | select-string "^(?!.*v4\.0\.30319).*")))
#- ps: $env:Path -split ';' | findstr /psi "msbuild"; cmd /c where msbuild.exe

- nuget restore -verbosity detailed
      
build: off
test: off
